name: Trifecta
favicon: null
layout_spectrum: 0.5419352266471833
typography_spectrum: 0.10458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e9e9e9'
    - '#cdcdcd'
    - '#f4673b'
    - '#9a9a9a'
  brandStrength: 0.5
  lightness: 0.9229765553027391
  saturation: 0.5362107157707214
  rhythmicContrast: 0.5
purpose: []
