name: Trifecta
favicon: null
layout_spectrum: 0.5419352266471833
typography_spectrum: 0.9747261377051473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1399822614621371
  lightness: 0.9229765553027391
  saturation: 0.5362107157707214
  rhythmicContrast: 0.40634433389641345
purpose: []
